// Static exercise encyclopedia — the "know every machine, every dumbbell
// exercise..." database from the coach's system prompt. Read-only reference
// data (no per-user storage needed), searchable by name/alias/muscle/
// equipment/category, and cross-checked against a user's health profile via
// `cautionFor` keywords that line up with the rules in lib/coach.ts.
import type { ExerciseCategory, ExerciseInfo, HealthProfile, MuscleGroup } from "@/types";

export const EXERCISES: ExerciseInfo[] = [
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    aliases: ["squat", "back squat"],
    category: "barbell",
    equipment: ["barbell", "squat rack"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core", "lower_back"],
    stabilizers: ["core", "lower_back"],
    difficulty: "intermediate",
    formTips: ["Brace core before descending", "Track knees over toes", "Keep chest up, neutral spine", "Descend to at least parallel"],
    commonMistakes: ["Knees caving inward", "Rounding the lower back at the bottom", "Rising hips before chest"],
    cautionFor: ["lumbar", "l4-l5", "disc", "knee", "hip"],
    alternatives: ["Leg Press", "Belt Squat", "Goblet Squat"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    aliases: ["45 degree leg press", "sled press"],
    category: "machine",
    equipment: ["leg press machine"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Keep lower back flat against the pad", "Don't lock knees out fully", "Control the negative"],
    commonMistakes: ["Letting lower back round off the pad at full depth", "Locking knees violently at the top"],
    cautionFor: ["knee"],
    alternatives: ["Barbell Back Squat", "Goblet Squat"],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    aliases: ["dumbbell goblet squat"],
    category: "dumbbell",
    equipment: ["dumbbell or kettlebell"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Hold weight at chest", "Elbows track inside knees at bottom", "Keep torso upright"],
    commonMistakes: ["Leaning too far forward", "Heels lifting off the floor"],
    cautionFor: ["knee"],
    alternatives: ["Bodyweight Squat", "Leg Press"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift (RDL)",
    aliases: ["rdl", "stiff leg deadlift"],
    category: "barbell",
    equipment: ["barbell"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "back"],
    stabilizers: ["core", "lower_back"],
    difficulty: "intermediate",
    formTips: ["Hinge at hips, soft knee bend", "Keep bar close to legs", "Neutral spine throughout"],
    commonMistakes: ["Rounding the back at the bottom", "Squatting the movement instead of hinging"],
    cautionFor: ["lumbar", "l4-l5", "disc", "lower back"],
    alternatives: ["Cable Pull-Through", "Machine Hip Thrust"],
  },
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    aliases: ["deadlift"],
    category: "barbell",
    equipment: ["barbell"],
    primaryMuscles: ["back", "glutes", "hamstrings"],
    secondaryMuscles: ["forearms", "core", "lower_back"],
    stabilizers: ["core", "lower_back", "forearms"],
    difficulty: "advanced",
    formTips: ["Bar over mid-foot", "Brace hard before pulling", "Push floor away, keep bar close"],
    commonMistakes: ["Rounding lower back off the floor", "Jerking the bar instead of a smooth pull"],
    cautionFor: ["lumbar", "l4-l5", "disc", "lower back", "cervical"],
    alternatives: ["Trap Bar Deadlift", "Machine Hip Thrust", "Cable Pull-Through"],
  },
  {
    id: "hip-thrust",
    name: "Barbell Hip Thrust",
    aliases: ["hip thrust"],
    category: "barbell",
    equipment: ["barbell", "bench"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Chin tucked, ribs down at lockout", "Drive through heels", "Pause and squeeze at the top"],
    commonMistakes: ["Overextending the lower back at lockout", "Bar rolling"],
    cautionFor: [],
    alternatives: ["Glute Bridge", "Cable Pull-Through"],
  },
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    aliases: ["bench press", "flat bench"],
    category: "barbell",
    equipment: ["barbell", "bench"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    stabilizers: ["shoulders", "core"],
    difficulty: "intermediate",
    formTips: ["Shoulder blades retracted and set", "Slight arch, feet planted", "Bar path touches lower chest"],
    commonMistakes: ["Flaring elbows to 90°", "Bouncing the bar off the chest"],
    cautionFor: ["shoulder"],
    alternatives: ["Machine Chest Press", "Dumbbell Bench Press", "Push-Up"],
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    aliases: ["chest press machine"],
    category: "machine",
    equipment: ["chest press machine"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Set seat so handles align with mid-chest", "Full controlled range of motion"],
    commonMistakes: ["Locking elbows out hard at the top"],
    cautionFor: [],
    alternatives: ["Push-Up", "Dumbbell Bench Press"],
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    aliases: ["incline db press"],
    category: "dumbbell",
    equipment: ["dumbbells", "incline bench"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    stabilizers: ["shoulders"],
    difficulty: "intermediate",
    formTips: ["30-45° incline", "Control dumbbells down to chest level", "Don't flare elbows past 75°"],
    commonMistakes: ["Setting incline too steep (becomes a shoulder press)"],
    cautionFor: ["shoulder"],
    alternatives: ["Machine Chest Press", "Push-Up"],
  },
  {
    id: "push-up",
    name: "Push-Up",
    aliases: ["pushup", "press up"],
    category: "bodyweight",
    equipment: ["none"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps", "core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Straight line head to heels", "Elbows ~45° from torso", "Full range of motion"],
    commonMistakes: ["Sagging hips", "Flaring elbows to 90°"],
    cautionFor: ["wrist"],
    alternatives: ["Incline Push-Up", "Machine Chest Press"],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    aliases: ["pulldown"],
    category: "cable",
    equipment: ["cable machine", "lat pulldown bar"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    stabilizers: ["forearms"],
    difficulty: "beginner",
    formTips: ["Pull to upper chest, elbows down and back", "Avoid leaning back excessively", "Control the eccentric"],
    commonMistakes: ["Using momentum/leaning back too far", "Pulling behind the neck"],
    cautionFor: ["shoulder"],
    alternatives: ["Assisted Pull-Up", "Seated Cable Row"],
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    aliases: ["cable row"],
    category: "cable",
    equipment: ["cable machine", "row handle"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts", "forearms"],
    stabilizers: ["core", "lower_back"],
    difficulty: "beginner",
    formTips: ["Neutral spine, hinge slightly forward at the hip", "Drive elbows back, squeeze shoulder blades", "Don't jerk the weight with torso lean"],
    commonMistakes: ["Excessive torso rocking", "Rounding the lower back"],
    cautionFor: ["lumbar", "lower back"],
    alternatives: ["Machine Row", "Lat Pulldown"],
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    aliases: ["pullup", "chin-up"],
    category: "calisthenics",
    equipment: ["pull-up bar"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "forearms", "rear_delts"],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Full hang to chin over bar", "Engage lats before pulling with arms", "Avoid kipping unless training explicitly for it"],
    commonMistakes: ["Partial range of motion", "Excessive swinging"],
    cautionFor: ["shoulder"],
    alternatives: ["Lat Pulldown", "Assisted Pull-Up Machine"],
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    aliases: ["db shoulder press", "seated dumbbell press"],
    category: "dumbbell",
    equipment: ["dumbbells", "bench (optional)"],
    primaryMuscles: ["shoulders", "front_delts"],
    secondaryMuscles: ["triceps"],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Press slightly forward, not straight up over ears", "Keep ribs down, avoid overarching lower back"],
    commonMistakes: ["Overarching the lower back", "Flaring elbows to full 90° at the bottom"],
    cautionFor: ["cervical", "neck", "shoulder", "lumbar"],
    alternatives: ["Machine Shoulder Press", "Landmine Press"],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    aliases: ["shoulder press machine"],
    category: "machine",
    equipment: ["shoulder press machine"],
    primaryMuscles: ["shoulders", "front_delts"],
    secondaryMuscles: ["triceps"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Seat height so handles start at shoulder level", "Controlled tempo, avoid locking out hard"],
    commonMistakes: ["Shrugging shoulders up into the neck during the press"],
    cautionFor: ["cervical", "neck", "shoulder"],
    alternatives: ["Lateral Raise", "Front Raise"],
  },
  {
    id: "lateral-raise",
    name: "Dumbbell Lateral Raise",
    aliases: ["side raise", "lat raise"],
    category: "dumbbell",
    equipment: ["dumbbells"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: ["shoulders"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Slight elbow bend, lead with elbows", "Raise to shoulder height, no higher", "Avoid using momentum"],
    commonMistakes: ["Shrugging traps to lift the weight", "Swinging the torso for momentum"],
    cautionFor: ["cervical", "neck"],
    alternatives: ["Cable Lateral Raise", "Machine Lateral Raise"],
  },
  {
    id: "face-pull",
    name: "Cable Face Pull",
    aliases: ["face pull"],
    category: "cable",
    equipment: ["cable machine", "rope attachment"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back", "shoulders"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Pull rope toward face, external rotation at the end", "Elbows high, squeeze shoulder blades"],
    commonMistakes: ["Pulling too low (toward chest instead of face)"],
    cautionFor: [],
    alternatives: ["Reverse Pec Deck", "Band Pull-Apart"],
  },
  {
    id: "barbell-curl",
    name: "Barbell Bicep Curl",
    aliases: ["bicep curl", "barbell curl"],
    category: "barbell",
    equipment: ["barbell (straight or EZ bar)"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Elbows pinned to sides", "Full range of motion, no swinging", "Control the eccentric"],
    commonMistakes: ["Swinging the torso to cheat the weight up", "Only doing half reps"],
    cautionFor: ["wrist"],
    alternatives: ["Dumbbell Hammer Curl", "Cable Curl"],
  },
  {
    id: "hammer-curl",
    name: "Dumbbell Hammer Curl",
    aliases: ["hammer curl"],
    category: "dumbbell",
    equipment: ["dumbbells"],
    primaryMuscles: ["biceps", "forearms"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Neutral grip throughout", "Elbows pinned to sides"],
    commonMistakes: ["Using momentum from the shoulders"],
    cautionFor: [],
    alternatives: ["Barbell Curl", "Cable Curl"],
  },
  {
    id: "tricep-pushdown",
    name: "Cable Tricep Pushdown",
    aliases: ["tricep pushdown", "pushdown"],
    category: "cable",
    equipment: ["cable machine", "bar or rope attachment"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Elbows pinned to sides", "Full extension without locking violently"],
    commonMistakes: ["Letting elbows drift forward, turning it into a chest movement"],
    cautionFor: ["wrist"],
    alternatives: ["Overhead Dumbbell Tricep Extension", "Dips"],
  },
  {
    id: "overhead-tricep-extension",
    name: "Overhead Dumbbell Tricep Extension",
    aliases: ["overhead extension", "skull crusher variant"],
    category: "dumbbell",
    equipment: ["dumbbell"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Elbows pointed forward and stationary", "Lower behind the head with control"],
    commonMistakes: ["Flaring elbows out wide", "Using too heavy a weight and losing control at the bottom"],
    cautionFor: ["shoulder", "cervical"],
    alternatives: ["Cable Tricep Pushdown"],
  },
  {
    id: "plank",
    name: "Plank",
    aliases: ["front plank"],
    category: "bodyweight",
    equipment: ["none"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "lower_back"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Straight line head to heels", "Squeeze glutes, brace core, don't hold breath"],
    commonMistakes: ["Hips sagging or piking up too high"],
    cautionFor: ["wrist", "shoulder"],
    alternatives: ["Dead Bug", "Bird Dog"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    aliases: [],
    category: "physiotherapy",
    equipment: ["none", "mat"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["lower_back"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Press lower back flat into the floor throughout", "Move opposite arm/leg slowly and with control"],
    commonMistakes: ["Letting the lower back arch off the floor"],
    cautionFor: [],
    alternatives: ["Bird Dog", "Plank"],
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    aliases: [],
    category: "physiotherapy",
    equipment: ["none", "mat"],
    primaryMuscles: ["lower_back", "core"],
    secondaryMuscles: ["glutes"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Keep hips and spine neutral, avoid rotating", "Extend opposite arm and leg slowly"],
    commonMistakes: ["Rotating the hips/rocking side to side"],
    cautionFor: [],
    alternatives: ["Dead Bug"],
  },
  {
    id: "mcgill-curl-up",
    name: "McGill Curl-Up",
    aliases: ["mcgill crunch"],
    category: "physiotherapy",
    equipment: ["none", "mat"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["lower_back"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["One knee bent, hands under lower back for support", "Lift head and shoulders slightly, spine stays rigid — no spinal flexion"],
    commonMistakes: ["Flexing through the lumbar spine instead of bracing rigidly"],
    cautionFor: [],
    alternatives: ["Plank", "Dead Bug"],
  },
  {
    id: "leg-curl",
    name: "Seated Leg Curl",
    aliases: ["hamstring curl"],
    category: "machine",
    equipment: ["leg curl machine"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Full range of motion", "Control the negative"],
    commonMistakes: ["Using momentum by rocking the hips"],
    cautionFor: ["knee"],
    alternatives: ["Romanian Deadlift", "Nordic Curl"],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    aliases: ["quad extension"],
    category: "machine",
    equipment: ["leg extension machine"],
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Controlled tempo, don't slam the weight stack", "Avoid hyperextending the knee at the top"],
    commonMistakes: ["Using momentum/jerking the weight up"],
    cautionFor: ["knee"],
    alternatives: ["Goblet Squat", "Leg Press"],
  },
  {
    id: "calf-raise",
    name: "Standing Calf Raise",
    aliases: ["calf raise"],
    category: "machine",
    equipment: ["calf raise machine or smith machine"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Full stretch at the bottom, full contraction at the top", "Slow and controlled"],
    commonMistakes: ["Bouncing at the bottom of the range"],
    cautionFor: [],
    alternatives: ["Seated Calf Raise"],
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    aliases: ["kb swing"],
    category: "strongman",
    equipment: ["kettlebell"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core", "lower_back", "shoulders"],
    stabilizers: ["core", "lower_back"],
    difficulty: "intermediate",
    formTips: ["Hip hinge, not a squat", "Power comes from the hips snapping forward", "Neutral spine throughout"],
    commonMistakes: ["Squatting the movement", "Rounding the back at the bottom of the backswing"],
    cautionFor: ["lumbar", "l4-l5", "disc", "lower back"],
    alternatives: ["Hip Thrust", "Romanian Deadlift"],
  },
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    aliases: ["farmer carry", "loaded carry"],
    category: "strongman",
    equipment: ["dumbbells or kettlebells or trap bar"],
    primaryMuscles: ["forearms", "core"],
    secondaryMuscles: ["back", "shoulders"],
    stabilizers: ["core", "lower_back"],
    difficulty: "beginner",
    formTips: ["Braced core, tall posture", "Shoulders down and back", "Even, controlled steps"],
    commonMistakes: ["Leaning to one side", "Shrugging shoulders up toward ears"],
    cautionFor: ["cervical", "neck", "lumbar"],
    alternatives: ["Suitcase Carry (single side, lighter)"],
  },
  {
    id: "power-clean",
    name: "Power Clean",
    aliases: ["clean"],
    category: "olympic_lift",
    equipment: ["barbell", "bumper plates"],
    primaryMuscles: ["glutes", "hamstrings", "shoulders"],
    secondaryMuscles: ["back", "quads", "forearms"],
    stabilizers: ["core", "lower_back"],
    difficulty: "advanced",
    formTips: ["Learn under a qualified coach first", "Bar stays close to the body throughout", "Triple extension before the pull-under"],
    commonMistakes: ["Pulling with the arms too early", "Rounding the back off the floor"],
    cautionFor: ["lumbar", "l4-l5", "disc", "cervical", "shoulder"],
    alternatives: ["Dumbbell High Pull", "Kettlebell Swing"],
  },
  {
    id: "box-jump",
    name: "Box Jump",
    aliases: [],
    category: "plyometric",
    equipment: ["plyo box"],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Land softly with bent knees", "Step down, don't jump down"],
    commonMistakes: ["Jumping down off the box (high impact on landing)"],
    cautionFor: ["knee", "lumbar"],
    alternatives: ["Squat Jump (lower box/no box)"],
  },
  {
    id: "battle-ropes",
    name: "Battle Ropes",
    aliases: [],
    category: "crossfit",
    equipment: ["battle ropes"],
    primaryMuscles: ["shoulders", "cardio"],
    secondaryMuscles: ["core", "forearms"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Athletic stance, knees soft", "Drive power from the core and legs, not just arms"],
    commonMistakes: ["Standing fully upright and only using the arms"],
    cautionFor: ["shoulder", "cervical"],
    alternatives: ["Rowing Machine", "Assault Bike"],
  },
  {
    id: "assault-bike",
    name: "Assault Bike",
    aliases: ["air bike", "fan bike"],
    category: "cardio",
    equipment: ["assault bike"],
    primaryMuscles: ["cardio"],
    secondaryMuscles: ["quads", "hamstrings", "shoulders"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Maintain upright posture", "Drive with both arms and legs evenly"],
    commonMistakes: ["Hunching over the handlebars"],
    cautionFor: [],
    alternatives: ["Rowing Machine", "Brisk Walking"],
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    aliases: ["erg", "concept 2"],
    category: "cardio",
    equipment: ["rowing machine"],
    primaryMuscles: ["back", "cardio"],
    secondaryMuscles: ["hamstrings", "biceps", "core"],
    stabilizers: ["core", "lower_back"],
    difficulty: "beginner",
    formTips: ["Legs, then hips, then arms on the drive — reverse on the recovery", "Keep back flat, don't round at the catch"],
    commonMistakes: ["Rounding the lower back at full compression", "Pulling with arms before legs finish driving"],
    cautionFor: ["lumbar", "lower back"],
    alternatives: ["Assault Bike", "Brisk Walking"],
  },
  {
    id: "brisk-walking",
    name: "Brisk Walking",
    aliases: ["treadmill walk", "incline walk"],
    category: "cardio",
    equipment: ["none or treadmill"],
    primaryMuscles: ["cardio"],
    secondaryMuscles: ["quads", "calves", "glutes"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Upright posture, natural arm swing", "Add incline for more intensity with low joint impact"],
    commonMistakes: [],
    cautionFor: [],
    alternatives: [],
  },
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    aliases: [],
    category: "resistance_band",
    equipment: ["resistance band"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back", "shoulders"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Arms straight, pull band apart at chest height", "Squeeze shoulder blades together"],
    commonMistakes: ["Bending the elbows too much, turning it into a row"],
    cautionFor: [],
    alternatives: ["Face Pull", "Reverse Pec Deck"],
  },
  {
    id: "cat-cow-stretch",
    name: "Cat-Cow Stretch",
    aliases: ["cat cow"],
    category: "mobility",
    equipment: ["mat"],
    primaryMuscles: ["lower_back"],
    secondaryMuscles: ["core", "neck"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Move slowly with the breath", "Full spinal segment articulation, not just the lower back"],
    commonMistakes: ["Rushing through the movement without control"],
    cautionFor: [],
    alternatives: [],
  },
  {
    id: "chin-tuck",
    name: "Chin Tuck",
    aliases: ["cervical retraction"],
    category: "physiotherapy",
    equipment: ["none"],
    primaryMuscles: ["neck"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Draw chin straight back (double chin), not down", "Hold 3-5 seconds, repeat gently"],
    commonMistakes: ["Tilting the head down instead of retracting straight back"],
    cautionFor: [],
    alternatives: [],
  },
  {
    id: "thoracic-extension-foam-roll",
    name: "Thoracic Extension on Foam Roller",
    aliases: ["t-spine extension"],
    category: "mobility",
    equipment: ["foam roller"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["core"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Roller placed at mid-back, hands supporting head", "Extend gently over the roller, avoid forcing the lower back"],
    commonMistakes: ["Letting the movement come from the lower back instead of the upper back"],
    cautionFor: ["cervical"],
    alternatives: [],
  },
  {
    id: "world's-greatest-stretch",
    name: "World's Greatest Stretch",
    aliases: ["lunge with rotation"],
    category: "mobility",
    equipment: ["none"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["core", "shoulders"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Full body warm-up flow — hip flexor stretch into a rotation", "Move slowly, breathe into each position"],
    commonMistakes: ["Rushing through without holding each position"],
    cautionFor: ["knee", "hip"],
    alternatives: [],
  },

  // --- Chest ---
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    aliases: ["db bench press", "flat dumbbell press"],
    category: "dumbbell",
    equipment: ["dumbbells", "bench"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    stabilizers: ["shoulders", "core"],
    difficulty: "intermediate",
    formTips: ["Retract shoulder blades before pressing", "Press dumbbells up and slightly inward", "Control the descent to chest level"],
    commonMistakes: ["Flaring elbows to 90°", "Letting dumbbells drift forward over the face"],
    cautionFor: ["shoulder"],
    alternatives: ["Machine Chest Press", "Barbell Bench Press"],
  },
  {
    id: "decline-bench-press",
    name: "Decline Barbell Bench Press",
    aliases: ["decline bench press"],
    category: "barbell",
    equipment: ["barbell", "decline bench"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    stabilizers: ["shoulders", "core"],
    difficulty: "intermediate",
    formTips: ["Secure feet/legs under the pads", "Bar path toward the lower chest", "Keep wrists stacked over elbows"],
    commonMistakes: ["Bouncing the bar off the chest", "Excessive arch beyond what's needed for stability"],
    cautionFor: ["shoulder"],
    alternatives: ["Barbell Bench Press", "Dumbbell Bench Press"],
  },
  {
    id: "dumbbell-fly",
    name: "Dumbbell Chest Fly",
    aliases: ["dumbbell fly", "flat dumbbell fly"],
    category: "dumbbell",
    equipment: ["dumbbells", "bench"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts"],
    stabilizers: ["shoulders", "core"],
    difficulty: "intermediate",
    formTips: ["Slight elbow bend held throughout the arc", "Lower until upper arms are roughly parallel to the floor", "Squeeze the chest at the top rather than banging dumbbells together"],
    commonMistakes: ["Lowering too deep and straining the shoulder joint", "Bending the elbows into a press"],
    cautionFor: ["shoulder"],
    alternatives: ["Cable Chest Fly", "Machine Chest Press"],
  },
  {
    id: "cable-chest-fly",
    name: "Cable Chest Fly",
    aliases: ["cable fly", "cable crossover"],
    category: "cable",
    equipment: ["cable machine", "handles"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Slight elbow bend maintained throughout", "Bring hands together in an arc at chest height", "Control the stretch, don't overextend the shoulder"],
    commonMistakes: ["Turning it into a press by bending the elbows too much", "Using momentum to swing the handles together"],
    cautionFor: ["shoulder"],
    alternatives: ["Dumbbell Chest Fly", "Machine Chest Press"],
  },
  {
    id: "dips",
    name: "Dips",
    aliases: ["chest dips", "tricep dips"],
    category: "calisthenics",
    equipment: ["dip bars or parallel bars"],
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_delts"],
    stabilizers: ["core", "shoulders"],
    difficulty: "intermediate",
    formTips: ["Lean forward to bias chest, stay upright to bias triceps", "Lower until shoulders are slightly below elbows", "Keep shoulders down, away from the ears"],
    commonMistakes: ["Descending too deep and straining the front of the shoulder", "Flaring elbows excessively"],
    cautionFor: ["shoulder", "wrist"],
    alternatives: ["Bench Dip", "Machine Chest Press", "Cable Tricep Pushdown"],
  },
  {
    id: "incline-push-up",
    name: "Incline Push-Up",
    aliases: [],
    category: "bodyweight",
    equipment: ["bench or elevated surface"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps", "core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Hands on an elevated surface, straight line head to heels", "Full range of motion down to the surface"],
    commonMistakes: ["Sagging hips"],
    cautionFor: ["wrist"],
    alternatives: ["Push-Up", "Machine Chest Press"],
  },

  // --- Back ---
  {
    id: "machine-row",
    name: "Machine Row",
    aliases: ["chest-supported row machine"],
    category: "machine",
    equipment: ["row machine"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Chest against the pad throughout", "Drive elbows back, squeeze shoulder blades", "Avoid shrugging at the top"],
    commonMistakes: ["Using momentum by pulling the torso off the pad"],
    cautionFor: [],
    alternatives: ["Seated Cable Row", "Single-Arm Dumbbell Row"],
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    aliases: ["chest supported t-bar row"],
    category: "machine",
    equipment: ["t-bar row machine or landmine attachment"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts", "forearms"],
    stabilizers: ["core", "lower_back"],
    difficulty: "intermediate",
    formTips: ["Neutral spine, hinge from the hips", "Pull the handles to the lower chest/upper abdomen", "Squeeze shoulder blades at the top"],
    commonMistakes: ["Rounding the lower back", "Using torso momentum to heave the weight"],
    cautionFor: ["lumbar", "lower back"],
    alternatives: ["Machine Row", "Seated Cable Row"],
  },
  {
    id: "single-arm-dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    aliases: ["db row", "one arm row"],
    category: "dumbbell",
    equipment: ["dumbbell", "bench"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    stabilizers: ["core", "lower_back"],
    difficulty: "beginner",
    formTips: ["Support the opposite hand/knee on a bench, flat back", "Pull the elbow up and back, close to the body", "Avoid rotating the torso"],
    commonMistakes: ["Twisting the torso to help lift the weight", "Rounding the lower back"],
    cautionFor: ["lumbar", "lower back"],
    alternatives: ["Machine Row", "Seated Cable Row"],
  },
  {
    id: "assisted-pull-up-machine",
    name: "Assisted Pull-Up Machine",
    aliases: ["assisted pull-up", "assisted pullup"],
    category: "machine",
    equipment: ["assisted pull-up machine"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "forearms", "rear_delts"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Set the counterweight to the lightest assistance you can control", "Full hang to chin over bar, same range as a pull-up"],
    commonMistakes: ["Relying on too much assistance and never progressing the range of motion"],
    cautionFor: ["shoulder"],
    alternatives: ["Lat Pulldown", "Pull-Up"],
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    aliases: ["cable pullover"],
    category: "cable",
    equipment: ["cable machine", "straight bar or rope"],
    primaryMuscles: ["back"],
    secondaryMuscles: ["core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Slight elbow bend held throughout", "Hinge slightly forward, pull the bar down to the thighs using the lats, not the arms"],
    commonMistakes: ["Bending the elbows to turn it into a pushdown"],
    cautionFor: ["shoulder"],
    alternatives: ["Lat Pulldown", "Machine Row"],
  },

  // --- Shoulders / delts / neck ---
  {
    id: "arnold-press",
    name: "Arnold Press",
    aliases: [],
    category: "dumbbell",
    equipment: ["dumbbells", "bench (optional)"],
    primaryMuscles: ["shoulders", "front_delts"],
    secondaryMuscles: ["triceps", "side_delts"],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Start palms facing you, rotate outward as you press overhead", "Keep ribs down, avoid overarching the lower back"],
    commonMistakes: ["Rushing the rotation instead of controlling it through the full press"],
    cautionFor: ["cervical", "neck", "shoulder", "lumbar"],
    alternatives: ["Dumbbell Shoulder Press", "Machine Shoulder Press"],
  },
  {
    id: "landmine-press",
    name: "Landmine Press",
    aliases: [],
    category: "barbell",
    equipment: ["barbell", "landmine attachment"],
    primaryMuscles: ["shoulders", "front_delts"],
    secondaryMuscles: ["triceps", "core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Press the bar up and slightly forward along its natural arc", "Brace the core, avoid overarching the lower back"],
    commonMistakes: ["Standing too upright and losing the natural pressing angle"],
    cautionFor: ["shoulder"],
    alternatives: ["Dumbbell Shoulder Press", "Machine Shoulder Press"],
  },
  {
    id: "front-raise",
    name: "Dumbbell Front Raise",
    aliases: ["front raise"],
    category: "dumbbell",
    equipment: ["dumbbells"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["shoulders"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Raise to shoulder height with a slight elbow bend", "Avoid swinging the torso for momentum", "Control the descent"],
    commonMistakes: ["Using momentum by leaning back", "Raising above shoulder height"],
    cautionFor: ["shoulder"],
    alternatives: ["Dumbbell Shoulder Press", "Dumbbell Lateral Raise"],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    aliases: [],
    category: "cable",
    equipment: ["cable machine", "single handle"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: ["shoulders"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Cable positioned low, at the side", "Lead with the elbow, raise to shoulder height", "Constant tension throughout, unlike dumbbells"],
    commonMistakes: ["Shrugging the trap to lift the weight"],
    cautionFor: ["cervical", "neck"],
    alternatives: ["Dumbbell Lateral Raise", "Machine Lateral Raise"],
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    aliases: ["rear delt fly machine"],
    category: "machine",
    equipment: ["pec deck machine"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Chest against the pad", "Lead with elbows, squeeze shoulder blades together at the back"],
    commonMistakes: ["Using too much weight and turning it into a short, jerky motion"],
    cautionFor: [],
    alternatives: ["Cable Face Pull", "Band Pull-Apart"],
  },
  {
    id: "bent-over-reverse-fly",
    name: "Bent-Over Dumbbell Reverse Fly",
    aliases: ["rear delt fly", "reverse fly"],
    category: "dumbbell",
    equipment: ["dumbbells"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back"],
    stabilizers: ["core", "lower_back"],
    difficulty: "beginner",
    formTips: ["Hinge at the hips, flat back", "Lead with elbows, raise to shoulder height", "Slight elbow bend held throughout"],
    commonMistakes: ["Rounding the lower back", "Using momentum by standing up out of the hinge"],
    cautionFor: ["lumbar", "lower back"],
    alternatives: ["Reverse Pec Deck", "Cable Face Pull"],
  },
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    aliases: ["shrug", "trap shrug"],
    category: "barbell",
    equipment: ["barbell"],
    primaryMuscles: ["neck"],
    secondaryMuscles: ["shoulders", "forearms"],
    stabilizers: ["forearms"],
    difficulty: "beginner",
    formTips: ["Lift straight up, shoulders toward the ears", "Avoid rolling the shoulders", "Control the descent"],
    commonMistakes: ["Rolling the shoulders in a circular motion instead of a straight vertical shrug", "Using momentum/bouncing the weight"],
    cautionFor: ["cervical", "neck"],
    alternatives: ["Dumbbell Shrug", "Four-Way Neck Machine"],
  },
  {
    id: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    aliases: ["shrug"],
    category: "dumbbell",
    equipment: ["dumbbells"],
    primaryMuscles: ["neck"],
    secondaryMuscles: ["shoulders", "forearms"],
    stabilizers: ["forearms"],
    difficulty: "beginner",
    formTips: ["Lift straight up, shoulders toward the ears", "Pause briefly at the top", "Control the descent"],
    commonMistakes: ["Using the biceps to help heave the weight up"],
    cautionFor: ["cervical", "neck"],
    alternatives: ["Barbell Shrug", "Four-Way Neck Machine"],
  },
  {
    id: "four-way-neck-machine",
    name: "Four-Way Neck Machine",
    aliases: ["neck machine", "weighted neck flexion/extension"],
    category: "machine",
    equipment: ["neck machine"],
    primaryMuscles: ["neck"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Start with light resistance and a small range of motion", "Move slowly and with control in all four directions (flexion, extension, and both lateral)"],
    commonMistakes: ["Jerking through the range of motion", "Using too much resistance too soon"],
    cautionFor: ["cervical", "neck"],
    alternatives: ["Chin Tuck", "Barbell Shrug"],
  },

  // --- Arms: biceps ---
  {
    id: "cable-curl",
    name: "Cable Curl",
    aliases: ["cable bicep curl"],
    category: "cable",
    equipment: ["cable machine", "straight or EZ bar attachment"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Elbows pinned to sides", "Constant tension throughout the range of motion"],
    commonMistakes: ["Swinging the torso to cheat the weight up"],
    cautionFor: ["wrist"],
    alternatives: ["Barbell Bicep Curl", "Dumbbell Hammer Curl"],
  },
  {
    id: "incline-dumbbell-curl",
    name: "Incline Dumbbell Curl",
    aliases: ["incline curl"],
    category: "dumbbell",
    equipment: ["dumbbells", "incline bench"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    stabilizers: [],
    difficulty: "intermediate",
    formTips: ["Let arms hang straight down for a deep stretch at the bottom", "Avoid letting the shoulders roll forward"],
    commonMistakes: ["Using momentum by swinging the shoulders forward"],
    cautionFor: ["shoulder"],
    alternatives: ["Barbell Bicep Curl", "Cable Curl"],
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    aliases: ["ez bar preacher curl"],
    category: "barbell",
    equipment: ["ez bar or barbell", "preacher bench"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    stabilizers: [],
    difficulty: "intermediate",
    formTips: ["Upper arms flat against the pad throughout", "Don't fully lock out the elbows at the bottom"],
    commonMistakes: ["Lifting the upper arms off the pad to cheat the weight up"],
    cautionFor: ["wrist"],
    alternatives: ["Barbell Bicep Curl", "Cable Curl"],
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    aliases: [],
    category: "dumbbell",
    equipment: ["dumbbell", "bench"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Elbow braced against the inside of the thigh", "Full range of motion, squeeze at the top"],
    commonMistakes: ["Using momentum by swinging the elbow off the thigh"],
    cautionFor: [],
    alternatives: ["Dumbbell Hammer Curl", "Cable Curl"],
  },

  // --- Arms: triceps ---
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    aliases: ["lying tricep extension", "ez bar skull crusher"],
    category: "barbell",
    equipment: ["ez bar or barbell", "bench"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Elbows stay pointed at the ceiling and stationary", "Lower the bar toward the forehead/behind the head with control"],
    commonMistakes: ["Letting elbows flare or drift backward, turning it into a pullover"],
    cautionFor: ["shoulder", "cervical"],
    alternatives: ["Cable Tricep Pushdown", "Overhead Dumbbell Tricep Extension"],
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    aliases: [],
    category: "barbell",
    equipment: ["barbell", "bench"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "front_delts"],
    stabilizers: ["shoulders", "core"],
    difficulty: "intermediate",
    formTips: ["Hands just inside shoulder width", "Elbows track close to the torso, not flared", "Bar path to the lower chest"],
    commonMistakes: ["Grip too narrow, straining the wrists", "Flaring elbows out wide"],
    cautionFor: ["shoulder", "wrist"],
    alternatives: ["Cable Tricep Pushdown", "Dips"],
  },
  {
    id: "bench-dip",
    name: "Bench Dip",
    aliases: [],
    category: "bodyweight",
    equipment: ["bench"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["front_delts", "chest"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Hands on the bench edge, fingers pointing forward", "Lower until upper arms are roughly parallel to the floor", "Keep shoulders down away from the ears"],
    commonMistakes: ["Descending too deep and straining the front of the shoulder", "Letting hips drift too far from the bench"],
    cautionFor: ["shoulder", "wrist"],
    alternatives: ["Dips", "Cable Tricep Pushdown"],
  },

  // --- Forearms ---
  {
    id: "wrist-curl",
    name: "Dumbbell Wrist Curl",
    aliases: ["wrist curl"],
    category: "dumbbell",
    equipment: ["dumbbells or barbell", "bench"],
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Forearms supported on the bench/thighs, wrists free to move", "Full range of motion, curl through the fingers at the bottom"],
    commonMistakes: ["Using too much weight and shortening the range of motion"],
    cautionFor: ["wrist"],
    alternatives: ["Dumbbell Reverse Wrist Curl", "Farmer's Carry"],
  },
  {
    id: "reverse-wrist-curl",
    name: "Dumbbell Reverse Wrist Curl",
    aliases: ["reverse wrist curl"],
    category: "dumbbell",
    equipment: ["dumbbells or barbell", "bench"],
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Forearms supported, palms facing down", "Small controlled range of motion, extend at the wrist"],
    commonMistakes: ["Using too much weight, which limits range of motion"],
    cautionFor: ["wrist"],
    alternatives: ["Dumbbell Wrist Curl", "Farmer's Carry"],
  },

  // --- Core ---
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    aliases: ["hanging knee raise"],
    category: "calisthenics",
    equipment: ["pull-up bar"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["forearms"],
    stabilizers: ["forearms", "core"],
    difficulty: "intermediate",
    formTips: ["Avoid swinging, control the movement", "Curl the pelvis under at the top for full ab engagement"],
    commonMistakes: ["Using momentum by swinging the legs", "Only moving from the hips without curling the pelvis"],
    cautionFor: ["shoulder", "lumbar"],
    alternatives: ["Plank", "Dead Bug"],
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    aliases: ["ab rollout"],
    category: "bodyweight",
    equipment: ["ab wheel"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "lower_back"],
    stabilizers: ["core", "shoulders"],
    difficulty: "advanced",
    formTips: ["Brace the core hard before rolling out", "Only roll out as far as you can maintain a neutral spine", "Squeeze glutes to protect the lower back"],
    commonMistakes: ["Letting the lower back sag/overarch as you roll out"],
    cautionFor: ["lumbar", "shoulder", "wrist"],
    alternatives: ["Plank", "Dead Bug"],
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    aliases: [],
    category: "bodyweight",
    equipment: ["none or dumbbell/medicine ball"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["lower_back"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Lean back to a stable angle, chest up", "Rotate from the torso, not just the arms", "Control the speed, avoid using momentum"],
    commonMistakes: ["Rounding the lower back", "Moving so fast that the core stops doing the work"],
    cautionFor: ["lower back"],
    alternatives: ["Cable Woodchopper", "Plank"],
  },
  {
    id: "cable-woodchopper",
    name: "Cable Woodchopper",
    aliases: ["woodchopper"],
    category: "cable",
    equipment: ["cable machine", "single handle"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders"],
    stabilizers: ["core", "lower_back"],
    difficulty: "intermediate",
    formTips: ["Rotate through the torso and hips together", "Keep arms relatively straight, let the core drive the motion"],
    commonMistakes: ["Rounding or hyperextending the lower back during the rotation"],
    cautionFor: ["lumbar", "lower back"],
    alternatives: ["Russian Twist", "Plank"],
  },

  // --- Lower back ---
  {
    id: "back-extension",
    name: "Back Extension",
    aliases: ["hyperextension"],
    category: "machine",
    equipment: ["hyperextension bench"],
    primaryMuscles: ["lower_back"],
    secondaryMuscles: ["glutes", "hamstrings"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Hinge from the hips, not the lower spine", "Rise to a neutral flat-back position, avoid overextending", "Squeeze glutes at the top"],
    commonMistakes: ["Hyperextending past neutral at the top", "Rounding the back at the bottom"],
    cautionFor: ["lumbar", "l4-l5", "disc", "lower back"],
    alternatives: ["Bird Dog", "Good Morning"],
  },
  {
    id: "good-morning",
    name: "Good Morning",
    aliases: [],
    category: "barbell",
    equipment: ["barbell"],
    primaryMuscles: ["lower_back", "hamstrings"],
    secondaryMuscles: ["glutes", "core"],
    stabilizers: ["core", "lower_back"],
    difficulty: "advanced",
    formTips: ["Bar on the upper back, soft knee bend", "Hinge at the hips with a neutral spine", "Start light — this is a technique-sensitive movement"],
    commonMistakes: ["Rounding the back at the bottom", "Bending the knees too much and turning it into a squat"],
    cautionFor: ["lumbar", "l4-l5", "disc", "lower back"],
    alternatives: ["Romanian Deadlift", "Back Extension"],
  },

  // --- Glutes ---
  {
    id: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    aliases: ["glute kickback"],
    category: "cable",
    equipment: ["cable machine", "ankle strap"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Slight forward lean, brace the core", "Drive the leg back and up using the glute, not the lower back"],
    commonMistakes: ["Overarching the lower back to increase range of motion"],
    cautionFor: ["lower back"],
    alternatives: ["Barbell Hip Thrust", "Glute Bridge"],
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    aliases: [],
    category: "bodyweight",
    equipment: ["none or mat"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Feet flat, drive through the heels", "Squeeze glutes at the top, avoid overextending the lower back"],
    commonMistakes: ["Overextending through the lower back instead of the hips"],
    cautionFor: [],
    alternatives: ["Barbell Hip Thrust", "Cable Glute Kickback"],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    aliases: ["rear foot elevated split squat"],
    category: "dumbbell",
    equipment: ["dumbbells", "bench"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Rear foot elevated on a bench, most weight in the front leg", "Descend until the front thigh is roughly parallel to the floor", "Keep torso upright"],
    commonMistakes: ["Letting the front knee cave inward", "Pushing off the rear foot too much"],
    cautionFor: ["knee", "hip"],
    alternatives: ["Walking Lunge", "Goblet Squat"],
  },

  // --- Quads ---
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    aliases: ["dumbbell walking lunge"],
    category: "dumbbell",
    equipment: ["dumbbells or none"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Step forward into a controlled lunge, front knee over ankle", "Keep torso upright", "Push through the front heel to the next step"],
    commonMistakes: ["Letting the front knee travel too far past the toes", "Taking steps too short, limiting range of motion"],
    cautionFor: ["knee", "hip"],
    alternatives: ["Bulgarian Split Squat", "Goblet Squat"],
  },
  {
    id: "front-squat",
    name: "Front Squat",
    aliases: [],
    category: "barbell",
    equipment: ["barbell", "squat rack"],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    stabilizers: ["core", "forearms"],
    difficulty: "advanced",
    formTips: ["Bar racked across the front delts, elbows high", "Stay upright through the torso", "Descend to at least parallel"],
    commonMistakes: ["Elbows dropping, causing the bar to roll forward", "Excessive forward lean"],
    cautionFor: ["knee", "wrist", "shoulder"],
    alternatives: ["Barbell Back Squat", "Goblet Squat"],
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    aliases: ["hack squat machine"],
    category: "machine",
    equipment: ["hack squat machine"],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    stabilizers: [],
    difficulty: "intermediate",
    formTips: ["Back flat against the pad throughout", "Feet positioned shoulder width, mid-pad", "Don't lock the knees out hard at the top"],
    commonMistakes: ["Letting the lower back round off the pad at the bottom"],
    cautionFor: ["knee"],
    alternatives: ["Leg Press", "Barbell Back Squat"],
  },

  // --- Hamstrings ---
  {
    id: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    aliases: ["nordic curl"],
    category: "calisthenics",
    equipment: ["partner or anchored pad"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes"],
    stabilizers: ["core"],
    difficulty: "advanced",
    formTips: ["Ankles anchored, hips extended and rigid", "Lower the torso forward as slowly as possible using the hamstrings", "Catch yourself with the hands at the bottom"],
    commonMistakes: ["Breaking at the hips instead of staying rigid", "Dropping too fast without control"],
    cautionFor: ["knee", "hamstring"],
    alternatives: ["Seated Leg Curl", "Romanian Deadlift"],
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Through",
    aliases: ["pull-through"],
    category: "cable",
    equipment: ["cable machine", "rope attachment"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back"],
    stabilizers: ["core", "lower_back"],
    difficulty: "beginner",
    formTips: ["Hinge at the hips facing away from the machine", "Rope pulls between the legs, drive the hips forward to stand", "Keep a neutral spine throughout"],
    commonMistakes: ["Squatting the movement instead of hinging", "Rounding the lower back"],
    cautionFor: ["lumbar", "lower back"],
    alternatives: ["Romanian Deadlift", "Barbell Hip Thrust"],
  },

  // --- Calves ---
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    aliases: [],
    category: "machine",
    equipment: ["seated calf raise machine"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Full stretch at the bottom, full contraction at the top", "Slow and controlled, avoid bouncing"],
    commonMistakes: ["Using a bouncing, partial range of motion"],
    cautionFor: [],
    alternatives: ["Standing Calf Raise", "Donkey Calf Raise"],
  },
  {
    id: "donkey-calf-raise",
    name: "Donkey Calf Raise",
    aliases: [],
    category: "machine",
    equipment: ["donkey calf raise machine"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Hinge forward at the hips, flat back", "Full stretch at the bottom, full contraction at the top"],
    commonMistakes: ["Rounding the lower back to get more stretch"],
    cautionFor: ["lower back"],
    alternatives: ["Standing Calf Raise", "Seated Calf Raise"],
  },

  // --- Cardio ---
  {
    id: "jump-rope",
    name: "Jump Rope",
    aliases: ["skipping rope"],
    category: "cardio",
    equipment: ["jump rope"],
    primaryMuscles: ["cardio"],
    secondaryMuscles: ["calves"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Small, quick hops, land softly on the balls of the feet", "Elbows close to the body, turn the rope from the wrists"],
    commonMistakes: ["Jumping too high, wasting energy", "Landing flat-footed"],
    cautionFor: ["knee"],
    alternatives: ["Assault Bike", "Brisk Walking"],
  },
  {
    id: "stationary-cycling",
    name: "Stationary Cycling",
    aliases: ["spin bike", "exercise bike"],
    category: "cardio",
    equipment: ["stationary bike"],
    primaryMuscles: ["cardio"],
    secondaryMuscles: ["quads", "hamstrings", "calves"],
    stabilizers: [],
    difficulty: "beginner",
    formTips: ["Seat height so the knee has a slight bend at the bottom of the pedal stroke", "Keep a relaxed grip and upright core"],
    commonMistakes: ["Seat set too low, adding unnecessary knee strain"],
    cautionFor: ["knee"],
    alternatives: ["Assault Bike", "Rowing Machine"],
  },
  {
    id: "stair-climber",
    name: "Stair Climber",
    aliases: ["stairmaster"],
    category: "cardio",
    equipment: ["stair climber machine"],
    primaryMuscles: ["cardio"],
    secondaryMuscles: ["quads", "glutes", "calves"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Stand upright, avoid leaning on the handrails", "Take full steps rather than short, rapid ones"],
    commonMistakes: ["Leaning heavily on the handrails, reducing the workload"],
    cautionFor: ["knee"],
    alternatives: ["Stationary Cycling", "Brisk Walking"],
  },

  // --- Compound / power variants referenced elsewhere as alternatives ---
  {
    id: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    aliases: ["hex bar deadlift"],
    category: "barbell",
    equipment: ["trap bar", "weight plates"],
    primaryMuscles: ["glutes", "hamstrings", "quads"],
    secondaryMuscles: ["back", "forearms", "core"],
    stabilizers: ["core", "lower_back", "forearms"],
    difficulty: "intermediate",
    formTips: ["Stand centered inside the bar", "Brace the core, push the floor away through the legs", "Keep the bar path vertical, close to the body"],
    commonMistakes: ["Rounding the lower back off the floor", "Hyperextending at the top"],
    cautionFor: ["lumbar", "l4-l5", "disc", "lower back"],
    alternatives: ["Conventional Deadlift", "Romanian Deadlift"],
  },
  {
    id: "machine-hip-thrust",
    name: "Machine Hip Thrust",
    aliases: ["hip thrust machine"],
    category: "machine",
    equipment: ["hip thrust machine"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilizers: ["core"],
    difficulty: "beginner",
    formTips: ["Chin tucked, ribs down at lockout", "Drive through the heels", "Pause and squeeze at the top"],
    commonMistakes: ["Overextending the lower back at lockout"],
    cautionFor: [],
    alternatives: ["Barbell Hip Thrust", "Glute Bridge"],
  },
  {
    id: "belt-squat",
    name: "Belt Squat",
    aliases: [],
    category: "machine",
    equipment: ["belt squat machine"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Weight is loaded via a belt at the hips, spine stays unloaded", "Descend to at least parallel, chest up"],
    commonMistakes: ["Leaning too far forward"],
    cautionFor: ["knee"],
    alternatives: ["Barbell Back Squat", "Leg Press"],
  },
  {
    id: "dumbbell-high-pull",
    name: "Dumbbell High Pull",
    aliases: ["high pull"],
    category: "dumbbell",
    equipment: ["dumbbells"],
    primaryMuscles: ["shoulders", "glutes"],
    secondaryMuscles: ["back", "hamstrings", "forearms"],
    stabilizers: ["core", "lower_back"],
    difficulty: "intermediate",
    formTips: ["Explosive hip extension drives the pull, not the arms", "Elbows lead and stay high, close to the body"],
    commonMistakes: ["Pulling with the arms first instead of the hips"],
    cautionFor: ["shoulder", "lumbar"],
    alternatives: ["Kettlebell Swing", "Power Clean"],
  },
  {
    id: "squat-jump",
    name: "Squat Jump",
    aliases: ["jump squat"],
    category: "plyometric",
    equipment: ["none"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "core"],
    stabilizers: ["core"],
    difficulty: "intermediate",
    formTips: ["Land softly with bent knees, absorb the impact", "Full squat depth on the way down before exploding up"],
    commonMistakes: ["Landing stiff-legged", "Knees caving inward on landing"],
    cautionFor: ["knee", "lumbar"],
    alternatives: ["Box Jump", "Goblet Squat"],
  },
];

// Exact-match index, built once, so name/alias lookups don't rescan the
// whole encyclopedia on every call (findExerciseByName runs per request on
// the identify-exercise fast path).
const EXERCISE_BY_EXACT_NAME = new Map<string, ExerciseInfo>();
for (const exercise of EXERCISES) {
  EXERCISE_BY_EXACT_NAME.set(exercise.name.toLowerCase(), exercise);
  for (const alias of exercise.aliases) EXERCISE_BY_EXACT_NAME.set(alias.toLowerCase(), exercise);
}

export function searchExercises(query?: string, filters?: { category?: ExerciseCategory; muscle?: MuscleGroup; equipment?: string }): ExerciseInfo[] {
  let results = EXERCISES;
  if (query) {
    const q = query.toLowerCase().trim();
    results = results.filter(
      (e) =>
        e.name.toLowerCase().includes(q) ||
        e.aliases.some((a) => a.toLowerCase().includes(q)) ||
        e.primaryMuscles.some((m) => m.includes(q)) ||
        e.secondaryMuscles.some((m) => m.includes(q)) ||
        e.category.includes(q) ||
        e.equipment.some((eq) => eq.toLowerCase().includes(q))
    );
  }
  if (filters?.category) results = results.filter((e) => e.category === filters.category);
  if (filters?.muscle) results = results.filter((e) => e.primaryMuscles.includes(filters.muscle!) || e.secondaryMuscles.includes(filters.muscle!));
  if (filters?.equipment) {
    const eq = filters.equipment.toLowerCase();
    results = results.filter((e) => e.equipment.some((x) => x.toLowerCase().includes(eq)));
  }
  return results;
}

export function findExerciseByName(name: string): ExerciseInfo | undefined {
  const q = name.toLowerCase().trim();
  return (
    EXERCISE_BY_EXACT_NAME.get(q) ||
    EXERCISES.find((e) => e.name.toLowerCase().includes(q) || e.aliases.some((a) => a.toLowerCase().includes(q)))
  );
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Cross-references an exercise's `cautionFor` keywords against the user's
// health conditions to flag safety and surface any historical context.
// Uses word-boundary matching rather than raw substring search — a plain
// `.includes("disc")` would match "shoulder discomfort" and wrongly flag
// spine-caution exercises for an unrelated condition.
//
// `safe`            – false only when an *active* (unresolved) condition matches.
// `reasons`         – keywords matched by active conditions (exercise may be unsafe).
// `historicalReasons` – keywords matched by resolved conditions (safe to do, but
//                     the AI should note the history and advise extra care).
export interface ExerciseSafety {
  safe: boolean;
  reasons: string[];
  historicalReasons: string[];
}

export function exerciseSafetyForProfile(exercise: ExerciseInfo, profile: HealthProfile): ExerciseSafety {
  const match = (text: string) =>
    exercise.cautionFor.filter((k) =>
      new RegExp(`\\b${escapeRegExp(k.toLowerCase())}\\b`).test(text)
    );

  const activeText = profile.conditions
    .filter((c) => !c.resolved)
    .map((c) => c.description.toLowerCase())
    .join(" | ");
  const historicalText = profile.conditions
    .filter((c) => c.resolved)
    .map((c) => c.description.toLowerCase())
    .join(" | ");

  const reasons = activeText ? match(activeText) : [];
  const historicalReasons = historicalText ? match(historicalText) : [];
  return { safe: reasons.length === 0, reasons, historicalReasons };
}
